### ISSUE TITLE
Builds currently not working on abs-cd.oscloud.info

### ISSUE THREAD

**Issue by fmauch** [bionade24/abs_cd#17]
Currently, I cannot trigger builds. The new container log (awesome, btw!) shows:

```
Traceback (most recent call last):
File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/opt/abs_cd/cd_manager/models.py", line 103, in build
built_packages = dep_pkgobj.build(force_rebuild=force_rebuild, built_packages=built_packages)
File "/opt/abs_cd/cd_manager/models.py", line 103, in build
built_packages = dep_pkgobj.build(force_rebuild=force_rebuild, built_packages=built_packages)
File "/opt/abs_cd/cd_manager/models.py", line 103, in build
built_packages = dep_pkgobj.build(force_rebuild=force_rebuild, built_packages=built_packages)
[Previous line repeated 8 more times]
File "/opt/abs_cd/cd_manager/models.py", line 107, in build
self.run_cd()
File "/opt/abs_cd/cd_manager/models.py", line 67, in run_cd
PackageSystem().build(self)
File "/opt/abs_cd/makepkg/makepkg.py", line 28, in __init__
image = PackageSystem.Connection().images.get('abs-cd/makepkg')
AttributeError: type object 'PackageSystem' has no attribute 'Connection'
```

**Comment by bionade24** [comment]
I should improve testing :|
